development:
  adapter: postgresql
  encoding: unicode
  database: beer_servings_development
  pool: 5
  username: DawnMariah  
  password: 

test:
  adapter: postgresql
  encoding: unicode
  database: beer_servings_test
  pool: 5
  username: DawnMariah
  password: 